[package]
name = "rover-std"
version = "0.1.0"
authors = ["Apollo Developers <opensource@apollographql.com>"]
edition = "2021"

publish = false

[dependencies]
atty = { workspace = true }
anyhow = { workspace = true }
camino = { workspace = true }
console = { workspace = true }
futures = { workspace = true }
notify = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }