[package]
name = "sputnik"
version = "0.0.0"
authors = ["Apollo Developers <opensource@apollographql.com>"]
edition = "2018"

[dependencies]
ci_info = { version = "0.11", features = ["serde-1"] }
reqwest =  { version = "0.10", features = ["blocking"] }
semver = { version = "0.11", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"
structopt = "0.3"
thiserror = "1.0"
url = "2.1"
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
assert_fs = "1.0"
